language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: FKVMn/dhOrofgS83jpvSs05oQVkrFDuONYoHJUp8WqYL726ffDY/tIYLlQ7B5B1aeKIMh0utU6GHxduAegChBwC2nGoGxsRQtkj6zKqPhQCNEyEmgv1eCysMuUNkc5sMY6ra/TieiBLBHShxRDZdfp64BCoInEJbcU22sfBwmPA=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: o4iqma24tnlUd3JWMi8yWjy8bsT7W+uF2niYcF8B49zz9+ottZKl+MRCcfPNOr/c5zssmh6otphSVyux7yTPsTLbZazOH7LMZq7o3+AsauaNEFZnyAViaKjFD+oRlZThYMFmVBQiy+qwK0hKMVJmqVfCfvWsE2GHNsJgt1oQvkI=
sudo: false
