language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: ncYiC5D4vv00gHqrn9vVOWbp3aB3KoyCxB2TrxnECJbx9JXJ/1Z9nxscJhR04W+qCbg+XyRctO4HIO/7yBtMUaGC/p9fwxSFP8jDX/N1EUGTtUw2xB99Eug8jABJuMapZ1pwkB6ERVmY3YOdVbc5aUDYEzLD+mGZsTiSLop0HWk=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: o4iqma24tnlUd3JWMi8yWjy8bsT7W+uF2niYcF8B49zz9+ottZKl+MRCcfPNOr/c5zssmh6otphSVyux7yTPsTLbZazOH7LMZq7o3+AsauaNEFZnyAViaKjFD+oRlZThYMFmVBQiy+qwK0hKMVJmqVfCfvWsE2GHNsJgt1oQvkI=
sudo: false
