language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: Czo8NBbdUZH0IfIaO98FuKUOxRolD12YRClyYSdHvjUoCO7NyiCD4Dv6li/x1rRWPt6wgFm0R6PKkpyh3bGWLhEMXjvpYOO6S+8Qt+5twvR1umiihJ/otBCVPdV5easylQgnSacMLU2n3zFwByo/vqZaF40m9H0hqfofZuR2tjI=
notifications:
  email: false
  slack:
    secure: B7SzTnNXvsI2ahNE+mehVzMSDMVQCmMfiaOKFiW6mVHb9XvG9kRKiQwKYkEAwEuFgctBnLhBBBgRy+5u5VqO2guoXRbzyJW9OlDIn3x3P77SlstWoqdGuiHQ7sS+Upd/2RvaFj5BvXgBLheWLypihLqDSlU+pUx2d1M0B9hKXsA=
sudo: false
